# Generated by Django 3.2.8 on 2022-04-05 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('game', '0001_initial'), ('game', '0002_quiz'), ('game', '0003_auto_20211016_1436'), ('game', '0004_auto_20211016_1827'), ('game', '0005_auto_20211016_1842'), ('game', '0006_delete_quiz'), ('game', '0007_quiz'), ('game', '0008_auto_20211017_2021'), ('game', '0009_auto_20211017_2022'), ('game', '0010_auto_20211017_2055'), ('game', '0011_auto_20211017_2104'), ('game', '0012_auto_20211017_2113'), ('game', '0013_match'), ('game', '0014_alter_quiz_unique_together'), ('game', '0015_alter_answerset_unique_together'), ('game', '0016_answersetlong_questionsetlong_quizlong'), ('game', '0017_auto_20211028_2204'), ('game', '0018_alter_answersetlong_quiz'), ('game', '0019_auto_20211028_2207'), ('game', '0020_auto_20211029_0724'), ('game', '0021_auto_20211029_0733'), ('game', '0022_auto_20211029_0754'), ('game', '0023_delete_answerset'), ('game', '0024_auto_20211029_0759'), ('game', '0025_rename_option0_questionset_option4'), ('game', '0026_alter_answer_unique_together'), ('game', '0027_alter_match_matched_at'), ('game', '0028_suggestion'), ('game', '0029_auto_20211108_1925'), ('game', '0030_auto_20211120_1501'), ('game', '0031_rename_question_set_quiz_question_sets'), ('game', '0032_auto_20211120_1642'), ('game', '0033_message'), ('game', '0034_auto_20211122_2115'), ('game', '0035_message_new'), ('game', '0036_post'), ('game', '0037_auto_20220114_2143'), ('game', '0038_alter_post_slug'), ('game', '0039_remove_post_header'), ('game', '0040_rename_content_post_body'), ('game', '0041_auto_20220125_1859'), ('game', '0042_alter_post_created'), ('game', '0043_post_updated'), ('game', '0044_delete_post'), ('game', '0045_auto_20220405_1853'), ('game', '0046_alter_answer_answer'), ('game', '0047_auto_20220405_2040')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='a', max_length=256)),
                ('option1', models.CharField(max_length=256)),
                ('option2', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('year', 'week')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('matched_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_user', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quiz2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256, verbose_name='pytanie')),
                ('option1', models.CharField(max_length=256, verbose_name='Odpowiedź 1')),
                ('option2', models.CharField(max_length=256, verbose_name='Odpowiedź 2')),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.questionset')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quiz')),
            ],
            options={
                'unique_together': {('quiz', 'question_index')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(through='game.QuizQuestion', to='game.Question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz_question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.quizquestion')),
            ],
            options={
                'unique_together': {('user', 'quiz_question')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('body', models.TextField(default=' ')),
                ('title', models.CharField(default=' ', max_length=1024)),
                ('new', models.BooleanField(default=True)),
            ],
        ),
    ]
