# Generated by Django 3.2.8 on 2021-10-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
                ('QuestionSet1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_set_1', to='game.questionset')),
                ('QuestionSet2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_set_2', to='game.questionset')),
            ],
        ),
    ]
