# Generated by Django 5.1.7 on 2025-04-13 11:21
import uuid
from django.db import migrations, models


def add_uuids(apps, schema_editor):
    Message = apps.get_model('game', 'Message')
    for message in Message.objects.all():
        message.uuid = uuid.uuid4()
        message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(default=None, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(add_uuids),
        migrations.AlterField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
