# Generated by Django 3.2.8 on 2021-10-16 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20211016_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionset',
            old_name='option4',
            new_name='option0',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet10',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet0',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='QuestionSet0', to='game.questionset'),
            preserve_default=False,
        ),
    ]
