# Generated by Django 3.2.8 on 2021-10-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20211016_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
