# Generated by Django 5.1.7 on 2025-04-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_message_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',)},
        ),
    ]
