# Generated by Django 3.2.8 on 2021-10-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
                ('QuestionSet0', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QuestionSet0', to='game.questionset')),
                ('QuestionSet1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QuestionSet1', to='game.questionset')),
                ('QuestionSet2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QuestionSet2', to='game.questionset')),
                ('QuestionSet3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QuestionSet3', to='game.questionset')),
                ('QuestionSet4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QuestionSet4', to='game.questionset')),
                ('QuestionSet5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QuestionSet5', to='game.questionset')),
                ('QuestionSet6', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QuestionSet6', to='game.questionset')),
                ('QuestionSet7', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QuestionSet7', to='game.questionset')),
                ('QuestionSet8', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QuestionSet8', to='game.questionset')),
                ('QuestionSet9', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QuestionSet9', to='game.questionset')),
            ],
        ),
    ]
