# Generated by Django 5.1.7 on 2025-04-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
