# Generated by Django 5.1.7 on 2025-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_post_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(max_length=300),
        ),
    ]
