# Generated by Django 3.2.8 on 2021-10-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet0',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet0',
            field=models.ManyToManyField(related_name='QuestionSet0', to='game.QuestionSet'),
        ),
    ]
