# Generated by Django 3.2.8 on 2021-10-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20211017_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet1',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet1',
            field=models.ManyToManyField(related_name='QuestionSet1', to='game.QuestionSet'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet2',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet2',
            field=models.ManyToManyField(related_name='QuestionSet2', to='game.QuestionSet'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet3',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet3',
            field=models.ManyToManyField(related_name='QuestionSet3', to='game.QuestionSet'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet4',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet4',
            field=models.ManyToManyField(related_name='QuestionSet4', to='game.QuestionSet'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet5',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet5',
            field=models.ManyToManyField(related_name='QuestionSet5', to='game.QuestionSet'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet6',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet6',
            field=models.ManyToManyField(related_name='QuestionSet6', to='game.QuestionSet'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet7',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet7',
            field=models.ManyToManyField(related_name='QuestionSet7', to='game.QuestionSet'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet8',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet8',
            field=models.ManyToManyField(related_name='QuestionSet8', to='game.QuestionSet'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet9',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet9',
            field=models.ManyToManyField(related_name='QuestionSet9', to='game.QuestionSet'),
        ),
    ]
