# Generated by Django 3.2.8 on 2021-10-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20211017_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet0',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet0',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='QuestionSet0', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet1',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet1',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='QuestionSet1', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet2',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet2',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='QuestionSet2', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet3',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet3',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='QuestionSet3', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet4',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet4',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='QuestionSet4', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet5',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet5',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='QuestionSet5', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet6',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet6',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='QuestionSet6', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet7',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet7',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='QuestionSet7', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet8',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet8',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='QuestionSet8', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet9',
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionSet9',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='QuestionSet9', to='game.questionset'),
            preserve_default=False,
        ),
    ]
