# Generated by Django 3.2.8 on 2021-10-17 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20211017_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet0',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet5',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet6',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet7',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet8',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionSet9',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_set0',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_set0', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_set1',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='question_set1', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_set2',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='question_set2', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_set3',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='question_set3', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_set4',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='question_set4', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_set5',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='question_set5', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_set6',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='question_set6', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_set7',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='question_set7', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_set8',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='question_set8', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_set9',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='question_set9', to='game.questionset'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer0', models.PositiveIntegerField()),
                ('answer1', models.PositiveIntegerField()),
                ('answer2', models.PositiveIntegerField()),
                ('answer3', models.PositiveIntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user')),
            ],
        ),
    ]
