# Generated by Django 5.1.7 on 2025-05-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='times_selected',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
