# Generated by Django 3.2.8 on 2021-10-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20211017_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerset',
            name='answer4',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerset',
            name='answer5',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerset',
            name='answer6',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerset',
            name='answer7',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerset',
            name='answer8',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerset',
            name='answer9',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
