# Generated by Django 5.1.7 on 2025-05-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_question_times_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='inne', max_length=64),
        ),
    ]
