# Generated by Django 3.2.8 on 2021-10-22 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20211017_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateField(auto_now_add=True)),
                ('matched_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_user', to='game.user')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='game.user')),
            ],
        ),
    ]
