# Generated by Django 3.2.8 on 2021-10-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_match'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('year', 'week')},
        ),
    ]
