# Generated by Django 3.2.8 on 2021-10-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_quiz_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerset',
            unique_together={('user', 'quiz')},
        ),
    ]
