# Generated by Django 3.2.8 on 2021-10-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_answerset_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSetLong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('option_number', models.PositiveIntegerField()),
                ('option', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='QuizLong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
                ('question_set_number', models.PositiveIntegerField()),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.questionset')),
            ],
            options={
                'unique_together': {('year', 'week', 'question_set_number')},
            },
        ),
        migrations.CreateModel(
            name='AnswerSetLong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_number', models.PositiveIntegerField()),
                ('answer_value', models.PositiveIntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user')),
            ],
            options={
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
