# Generated by Django 3.2.8 on 2021-10-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_answersetlong_questionsetlong_quizlong'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionSetLong',
        ),
        migrations.RenameField(
            model_name='answersetlong',
            old_name='answer_number',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='answersetlong',
            old_name='answer_value',
            new_name='answer_index',
        ),
        migrations.RenameField(
            model_name='quizlong',
            old_name='question_set_number',
            new_name='question_set_index',
        ),
        migrations.AlterUniqueTogether(
            name='quizlong',
            unique_together={('year', 'week', 'question_set_index')},
        ),
    ]
