# Generated by Django 3.2.8 on 2021-10-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_answersetlong_quiz'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizlong',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quizlong',
            name='question_set',
        ),
        migrations.DeleteModel(
            name='AnswerSetLong',
        ),
        migrations.DeleteModel(
            name='QuizLong',
        ),
    ]
