# Generated by Django 3.2.8 on 2021-10-29 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20211028_2207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerset',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='QuizItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
                ('question_set_index', models.PositiveIntegerField()),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.questionset')),
            ],
            options={
                'unique_together': {('year', 'week')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveIntegerField()),
                ('quiz_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quizitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user')),
            ],
        ),
    ]
