# Generated by Django 3.2.8 on 2021-10-29 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20211029_0724'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizitem',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Quiz2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('year', 'week')},
            },
        ),
        migrations.RemoveField(
            model_name='quizitem',
            name='week',
        ),
        migrations.RemoveField(
            model_name='quizitem',
            name='year',
        ),
        migrations.AddField(
            model_name='quizitem',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.quiz2'),
            preserve_default=False,
        ),
    ]
