# Generated by Django 3.2.8 on 2021-10-29 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20211029_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerset',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quiz2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quiz2'),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
