# Generated by Django 3.2.8 on 2021-10-29 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20211029_0754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerSet',
        ),
    ]
