# Generated by Django 3.2.8 on 2021-10-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_delete_answerset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz2',
            new_name='Quiz',
        ),
        migrations.AlterUniqueTogether(
            name='quizitem',
            unique_together={('quiz', 'question_set_index')},
        ),
    ]
