# Generated by Django 3.2.8 on 2021-10-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_auto_20211029_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionset',
            old_name='option0',
            new_name='option4',
        ),
    ]
