# Generated by Django 3.2.8 on 2021-11-08 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0028_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='matched_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='option1',
            field=models.CharField(max_length=256, verbose_name='Odpowiedź 1'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='option2',
            field=models.CharField(max_length=256, verbose_name='Odpowiedź 2'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='option3',
            field=models.CharField(max_length=256, verbose_name='Odpowiedź 3'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='option4',
            field=models.CharField(max_length=256, verbose_name='Odpowiedź 4'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='question',
            field=models.CharField(max_length=256, verbose_name='pytanie'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
