# Generated by Django 3.2.8 on 2021-11-20 14:01

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_auto_20211108_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_set_index', models.PositiveIntegerField(validators=[game.models.validate_less_or_equal_to_ten])),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.questionset')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_set',
            field=models.ManyToManyField(through='game.QuizQuestionSet', to='game.QuestionSet'),
        ),
    ]
