# Generated by Django 3.2.8 on 2021-11-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_auto_20211120_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='question_set',
            new_name='question_sets',
        ),
    ]
