# Generated by Django 3.2.8 on 2021-11-20 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0031_rename_question_set_quiz_question_sets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionSet',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='QuizQuestionSet',
            new_name='QuizQuestion',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='question_set',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='question_set_index',
            new_name='question_index',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_sets',
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.quizquestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(through='game.QuizQuestion', to='game.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'quiz_question')},
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'question_index')},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='quiz_item',
        ),
        migrations.DeleteModel(
            name='QuizItem',
        ),
    ]
