# Generated by Django 3.2.8 on 2021-11-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_auto_20211122_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
