# Generated by Django 3.2.8 on 2022-01-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header',
        ),
    ]
