# Generated by Django 3.2.8 on 2022-01-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_remove_post_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='body',
        ),
    ]
