# Generated by Django 3.2.8 on 2022-01-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_rename_content_post_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created',
        ),
    ]
