# Generated by Django 3.2.8 on 2022-04-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_post_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
