# Generated by Django 3.2.8 on 2022-04-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0044_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='option4',
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
