# Generated by Django 3.2.8 on 2022-04-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0046_alter_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='a', max_length=256),
            preserve_default=False,
        ),
    ]
