# Generated by Django 3.2.8 on 2022-06-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_auto_20220405_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('slug', models.SlugField(max_length=250)),
                ('created', models.DateField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
